/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 12/05/2010, 11:42:47
 */
package manager;

import business.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneLayout;
import javax.swing.border.LineBorder;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Shirkit
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();

        // This thing here is working along with formComponentShown to solve the fucking bug of not showing the correct size when running the app
        this.setResizable(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenu = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        itemApplyMods = new javax.swing.JMenuItem();
        itemUnpplyAllMods = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemUpdateMods = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemExit = new javax.swing.JMenuItem();
        menuOptions = new javax.swing.JMenu();
        itemChangePath = new javax.swing.JMenuItem();
        itemChangePathManually = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuHelp = new javax.swing.JMenu();
        itemVisitForumThread = new javax.swing.JMenuItem();
        itemVisitSourceforge = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        mainMenu.setName("mainMenu"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(manager.ManagerApp.class).getContext().getResourceMap(NewJFrame.class);
        menuFile.setText(resourceMap.getString("menuFile.text")); // NOI18N
        menuFile.setName("menuFile"); // NOI18N

        itemApplyMods.setText(resourceMap.getString("itemApplyMods.text")); // NOI18N
        itemApplyMods.setName("itemApplyMods"); // NOI18N
        itemApplyMods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemApplyModsActionPerformed(evt);
            }
        });
        menuFile.add(itemApplyMods);

        itemUnpplyAllMods.setText(resourceMap.getString("itemUnpplyAllMods.text")); // NOI18N
        itemUnpplyAllMods.setName("itemUnpplyAllMods"); // NOI18N
        menuFile.add(itemUnpplyAllMods);

        jSeparator1.setName("jSeparator1"); // NOI18N
        menuFile.add(jSeparator1);

        itemUpdateMods.setText(resourceMap.getString("itemUpdateMods.text")); // NOI18N
        itemUpdateMods.setName("itemUpdateMods"); // NOI18N
        menuFile.add(itemUpdateMods);

        jSeparator2.setName("jSeparator2"); // NOI18N
        menuFile.add(jSeparator2);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(manager.ManagerApp.class).getContext().getActionMap(NewJFrame.class, this);
        itemExit.setAction(actionMap.get("quit")); // NOI18N
        itemExit.setText(resourceMap.getString("itemExit.text")); // NOI18N
        itemExit.setName("itemExit"); // NOI18N
        menuFile.add(itemExit);

        mainMenu.add(menuFile);

        menuOptions.setText(resourceMap.getString("menuOptions.text")); // NOI18N
        menuOptions.setName("menuOptions"); // NOI18N

        itemChangePath.setText(resourceMap.getString("itemChangePath.text")); // NOI18N
        itemChangePath.setName("itemChangePath"); // NOI18N
        itemChangePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemChangePathActionPerformed(evt);
            }
        });
        menuOptions.add(itemChangePath);

        itemChangePathManually.setText(resourceMap.getString("itemChangePathManually.text")); // NOI18N
        itemChangePathManually.setName("itemChangePathManually"); // NOI18N
        itemChangePathManually.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemChangePathManuallyActionPerformed(evt);
            }
        });
        menuOptions.add(itemChangePathManually);

        jSeparator3.setName("jSeparator3"); // NOI18N
        menuOptions.add(jSeparator3);

        mainMenu.add(menuOptions);

        menuHelp.setText(resourceMap.getString("menuHelp.text")); // NOI18N
        menuHelp.setName("menuHelp"); // NOI18N

        itemVisitForumThread.setText(resourceMap.getString("itemVisitForumThread.text")); // NOI18N
        itemVisitForumThread.setName("itemVisitForumThread"); // NOI18N
        menuHelp.add(itemVisitForumThread);

        itemVisitSourceforge.setText(resourceMap.getString("itemVisitSourceforge.text")); // NOI18N
        itemVisitSourceforge.setName("itemVisitSourceforge"); // NOI18N
        menuHelp.add(itemVisitSourceforge);

        jSeparator4.setName("jSeparator4"); // NOI18N
        menuHelp.add(jSeparator4);

        itemAbout.setText(resourceMap.getString("itemAbout.text")); // NOI18N
        itemAbout.setName("itemAbout"); // NOI18N
        itemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAboutActionPerformed(evt);
            }
        });
        menuHelp.add(itemAbout);

        mainMenu.add(menuHelp);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-698)/2, (screenSize.height-516)/2, 698, 516);
    }// </editor-fold>//GEN-END:initComponents

    private void itemApplyModsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemApplyModsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemApplyModsActionPerformed

    private void itemChangePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemChangePathActionPerformed
        JFileChooser f = new JFileChooser();
        f.setDialogType(JFileChooser.OPEN_DIALOG);
        f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        f.setDialogTitle("Select the HoN folder");
        f.showOpenDialog(this);
        try {
            Game.getInstance().setPath(f.getSelectedFile());
            System.out.println(Game.getInstance().getVersion());
        } catch (FileNotFoundException ex) {
            if (ex.getMessage().equalsIgnoreCase("Hon folder doesn't exist")) {
                JOptionPane.showMessageDialog(this, "HoN folder doesn't seem to exist.\nPlease, be sure to set a valid folder path.", "HoN folder error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "HoN launcher couldn't be found.\nPlease, be sure to set a valid folder path.", "HoN launcher error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "For some reason, the HoN launcher couldn't be open.", "Random I/O Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemChangePathActionPerformed

    private void itemChangePathManuallyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemChangePathManuallyActionPerformed
        try {
            Game.getInstance().setPath(new File(JOptionPane.showInputDialog(null, "Enter the full path to the game", "Enter", JOptionPane.QUESTION_MESSAGE)));
        } catch (FileNotFoundException ex) {
            if (ex.getMessage().equalsIgnoreCase("Hon folder doesn't exist")) {
                JOptionPane.showMessageDialog(this, "HoN folder doesn't seem to exist.\nPlease, be sure to set a valid folder path.", "HoN folder error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "HoN launcher couldn't be found.\nPlease, be sure to set a valid folder path.", "HoN launcher error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "For some reason, the HoN launcher couldn't be open.", "Random I/O Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemChangePathManuallyActionPerformed

    private void itemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAboutActionPerformed
        ManagerAboutBox about = new ManagerAboutBox(this);
        about.setLocation(this.getX() + 20, this.getY() + 20);
        about.setVisible(true);
    }//GEN-LAST:event_itemAboutActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:)
        this.setResizable(true);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     * @deprecated this isn't suposed to be called.
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAbout;
    private javax.swing.JMenuItem itemApplyMods;
    private javax.swing.JMenuItem itemChangePath;
    private javax.swing.JMenuItem itemChangePathManually;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemUnpplyAllMods;
    private javax.swing.JMenuItem itemUpdateMods;
    private javax.swing.JMenuItem itemVisitForumThread;
    private javax.swing.JMenuItem itemVisitSourceforge;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuOptions;
    // End of variables declaration//GEN-END:variables
}
